### ISSUE TITLE
A Typo

### ISSUE THREAD

**Issue by Zhang-Yihao** [chrisliu298/awesome-representation-engineering#1]
Hi, I noticed that there is a typo in the _Note_ part:

If you believe your paper on **LLM unlearning** is not included, or if you find a mistake, typo, or information that is not up to date, please open an issue, and I will address it as soon as possible.

The "LLM unlearning" should be replaced by "Representation Engineering". This is possibly due to directly duplicating the document in awesome llm unlearning.

Despite this, I am truly appreciated to notice that there are efforts for this topic. I am glad that our paper is included in this repo! If anyone is interested in our work, feel free to contact with us. We'd be glad to get any feedback as this paper is still in a preliminary stage!

**Comment by chrisliu298** [comment]
Hi @Zhang-Yihao. Thanks for noticing it! Yes, that was because I reused the README template from my other repo, and I have fixed the typo.

Thank you for the feedback and I hope this repository proves useful for your research.
